# Generated by Django 5.0.6 on 2024-05-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "species_type",
                    models.CharField(
                        choices=[("bird", "Bird"), ("insect", "Insect")], max_length=50
                    ),
                ),
                ("species_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("habitat", models.CharField(max_length=100)),
                ("size", models.CharField(max_length=50)),
                ("extinction_status", models.CharField(max_length=50)),
            ],
        ),
    ]
